#!/usr/bin/env bash

# set default sagetv home
SAGE_HOME=${SAGE_HOME:-/opt/sagetv/server}

# set java memory
if [ "${JAVA_MEM_MB}" != "" ] ; then
    echo "Updating Java Mem"
    if [ ! -e ${SAGE_HOME}/sagesettings.old ]; then
        if [ -e ${SAGE_HOME}/sagesettings ] ; then
            cp ${SAGE_HOME}/sagesettings ${SAGE_HOME}/sagesettings.old
        fi
    fi

    ## hack
    if  [ "$OPT_JSTATD" == "Y" ] ; then
        EXTRA_ARGS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    fi
    # JAVAMEM=-Xmx768m
    echo "export JAVAMEM=\"-Xmx${JAVA_MEM_MB}m ${EXTRA_ARGS}\"" > ${SAGE_HOME}/sagesettings
    chmod 755 ${SAGE_HOME}/sagesettings
else
    if  [ "$OPT_JSTATD" == "Y" ] ; then
        EXTRA_ARGS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

        if [ ! -e ${SAGE_HOME}/sagesettings.old ]; then
            if [ -e ${SAGE_HOME}/sagesettings ] ; then
                cp ${SAGE_HOME}/sagesettings ${SAGE_HOME}/sagesettings.old
            fi
        fi

    # hack to add more args
    echo "export JAVAMEM=\"${EXTRA_ARGS}\"" > ${SAGE_HOME}/sagesettings
    chmod 755 ${SAGE_HOME}/sagesettings
    fi
fi

