#!/bin/sh

# start the server
cd /opt/sagetv/server/

if [ -x /opt/sagetv/server/sagetv-user-script.sh ] ; then
    sudo -u sagetv /opt/sagetv/server/sagetv-user-script.sh
fi

sudo -u sagetv /opt/sagetv/server/startsage

exit 0